services:
    sgrunty:
        image: sgruntbot:latest
        environment:
            CHAT_ID: -676046724
            TELEGRAM_TOKEN: PUT_YOUR_TOKEN_HERE
            IMGUR_CLIENT_ID: Dummy
            spring_profiles_active: docker
        depends_on:
            mariadb:
                condition: service_healthy

    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: sgrunt
            MYSQL_USER: sgrunt
            MYSQL_PASSWORD: sgrunt
            MYSQL_DATABASE: sgrunt
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
        volumes:
            - ./sgrunt_db/:/var/lib/mysql
        ports:
            - "127.0.0.1:3307:3306"