services:
    sgrunty:
        image: sgruntbot:latest
        environment:
            CHAT_ID: -676046724
            TELEGRAM_TOKEN: PUT_YOUR_TOKEN_HERE
            IMGUR_CLIENT_ID: Dummy
            spring_profiles_active: docker
        depends_on:
            mariadb:
                condition: service_healthy
        build:
            dockerfile_inline: |
                FROM debian:bookworm-slim
                COPY sgruntbot-2.0.140.jar ./sgruntbot.jar
                RUN apt update && apt install wget libfreetype6 fontconfig fonts-unfonts-core fonts-arphic-ukai fonts-arphic-uming -y
                RUN wget https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb
                RUN dpkg -i jdk-21_linux-x64_bin.deb
                CMD ["java", "-jar", "./sgruntbot.jar"]

    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: sgrunt
            MYSQL_USER: sgrunt
            MYSQL_PASSWORD: sgrunt
            MYSQL_DATABASE: sgrunt
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
        volumes:
            - ./sgrunt_db/:/var/lib/mysql
        ports:
            - "127.0.0.1:3307:3306"